#!/usr/bin/python

# The usual preamble
import numpy as np
import pandas as pd
import lib.pandasNVL as pdNVL
import time

# Get data (NYC 311 service request dataset) and start cleanup
na_values = ['NO CLUE', 'N/A', '0']
raw_requests = pd.read_csv('~/Documents/weld/pandas/data/311-service-requests.csv', na_values=na_values, dtype={'Incident Zip': str})
requests = pdNVL.DataFrameNVL(raw_requests)
print "Done reading input file..."

start = time.time()
# print len(requests['Incident Zip'].unique().evaluate())

# Fix requests with extra digits
requests['Incident Zip'] = requests['Incident Zip'].str.slice(0, 5)

# Fix requests with 00000 zipcodes
zips_predicate0 = requests['Incident Zip'] == '00000'
requests['Incident Zip'][zips_predicate0] = "nan"

# Fix requests with 92123 zipcodes
zips_predicate1 = requests['Incident Zip'] == '92123'
requests['Incident Zip'][zips_predicate1] = "nan"

# Fix requests with 11575 zipcodes
zips_predicate2 = requests['Incident Zip'] == '11575'
requests['Incident Zip'][zips_predicate2] = "nan"

# Fix requests with 10466 zipcodes
zips_predicate3 = requests['Incident Zip'] == '10466'
requests['Incident Zip'][zips_predicate3] = "nan"

# Fix requests with 13221 zipcodes
zips_predicate4 = requests['Incident Zip'] == '13221'
requests['Incident Zip'][zips_predicate4] = "nan"

# Display unique incident zips again (this time cleaned)
print len(requests['Incident Zip'].unique().evaluate())
end = time.time()

print "Total end-to-end time: %.2f" % (end - start)
